custom_categories:
  - name: Programming Guides
    children:
      - README
      - Quick Start
      - Main Programming Guide
  - name: Main Symbols
    children:
      - NoiseTagging
      - NoiseTagController
      - NoiseTagControl
      - NoiseTagControlProperties
      - NoiseTagDelegate
  - name: Controls
    children:
      - NoiseTagControlAppearance
      - NoiseTagButtonView
      - NoiseTagShapeButtonView
      - NoiseTagLabeledButtonView
      - LocationLabel
      - NoiseTagCheckBoxView
      - NoiseTagRadioButton
      - NoiseTagPopupButtonView
      - NoiseTagPopupItem
  - name: Keyboard
    children:
      - NoiseTagKeyboardViewController
      - NoiseTaggingKeyboardDelegate
      - SetOfSettingsNoiseTagKeyboard
      - NoiseTagKeyboardSettingTitles
      - CustomizableButtonState
      - StandardCustomizableKeyboardButton
      - LettersLayoutType
  - name: Settings
    children:
      - Setting
      - NoiseTagSetOfSettings
      - SetOfSettings
      - NoiseTagSettingTitles
      - BoolSetting
      - IntSetting
      - DoubleSetting
      - TextSetting
      - EnumSetting
      - EnumAsSetting
      - ItemOfArraySetting
      - ItemOfArrayInMenu
      - ColorSetting
      - PickableColor
      - ResultValidityCheck
      - Setting_abstract
      - SettingObserver
      - SettingSubscriber

      
module: NoiseTagging

copyright: MindAffect 2020

min_acl: public

documentation: "*.md"

xcodebuild_arguments: [-UseModernBuildSystem=YES]
